"""Restructure postmortem_tests table with comprehensive autopsy fields

Revision ID: 6e9b24914c73
Revises: 5c6451f0cc9b
Create Date: 2025-11-09 18:30:29.236753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9b24914c73'
down_revision = '5c6451f0cc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postmortem_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('autopsy_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('official_death_cause', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('final_disease_diagnosis', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('macro_findings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('micro_histology', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('toxicology_results', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('genetic_results', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('clinical_pathologic_correlation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_postmortem_tests_disease_code', 'diseases', ['final_disease_diagnosis'], ['code'])
        batch_op.drop_column('category')
        batch_op.drop_column('findings_description')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postmortem_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('findings_description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_postmortem_tests_disease_code', type_='foreignkey')
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('clinical_pathologic_correlation')
        batch_op.drop_column('genetic_results')
        batch_op.drop_column('toxicology_results')
        batch_op.drop_column('micro_histology')
        batch_op.drop_column('macro_findings')
        batch_op.drop_column('final_disease_diagnosis')
        batch_op.drop_column('official_death_cause')
        batch_op.drop_column('autopsy_date')
        batch_op.drop_column('case_id_reference')

    # ### end Alembic commands ###
